#!/bin/bash

main() {
    local OLD_PYTHONPATH=$PYTHONPATH
    local THIS_DIR=""
    THIS_DIR=$(pwd)
    if [ -z "${VIRTUAL_ENV}" ]; then
        echo "Please run: source do/setup"
        exit 1
    fi
    export PYTHONPATH=$THIS_DIR:$PYTHONPATH

    # Remove garbage files that may be around from tests.
    find . -name "*.pyc" -type f -delete; find . -name "__pycache__" -type d -prune -exec rm -rf '{}' \;
    
    pip install -U pytest-xdist

    py.test -f ./tests

    export PYTHONPATH=$OLD_PYTHONPATH
}
main "$@"
