#!/bin/bash -e
if [ -z "${VIRTUAL_ENV}" ]; then
    echo "Please run: source do/setup"
    exit 1
fi

echo "---------------------------------"
pip install 'setuptools==38.5.2'
echo "PIP FREEZE"
pip freeze
which python3
echo "---------------------------------"

python3 setup.py bdist_wheel --universal
