#!/usr/bin/env bash
dir="$( cd "$( dirname "$0" )" && pwd )"
cd $dir/..

check=false
isort=false
while getopts ":cs" opt; do
    case $opt in
    c)  check=true
        ;;
    s)  isort=true
        ;;
    esac
done


if [ "$check" == "true" ]; then
    if [ "$isort" == "true" ]; then
        isort -rc -c ./granular_configuration tests
    fi
    black -l 120 --check ./granular_configuration tests
else
    if [ "$isort" == "true" ]; then
        isort -rc ./granular_configuration tests
    fi
    black -l 120 ./granular_configuration tests
fi

