name: linting

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint[ruff isort, ruff, bandit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pipx install poetry
      - run: poetry install
      - run: poetry run ./run _lint

  mypy:
    name: Lint[mypy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pipx install poetry
      - run: poetry install
      - run: poetry run ./run _mypy

  pyright:
    name: Lint[pyright]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pipx install poetry
      - run: poetry install --with=pyright
      - run: poetry run ./run _pyright
