name: linting

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pipx install poetry
      - run: poetry install
      - run: poetry run ./run _lint
